### ISSUE TITLE
Related packages 

### ISSUE THREAD

**Issue by cortner** [libAtoms/ExtXYZ.jl#1]
https://github.com/SimonEnsemble/Xtals.jl

https://github.com/jgreener64/pdb-benchmarks

**Comment by cortner** [comment]
And supposedly there is a jl interface somewhere for 

https://chemfiles.org/

**Comment by jameskermode** [comment]
Thanks - this will just be a lightweight Julia front end for the C code in https://github.com/libAtoms/extxyz, which is @noam and my reimplementation of extended XYZ format with a well-defined specification. The idea is to have exactly one parser, partially auto-generated from the spec, usually from C, Fortran, Julia and Python, which QUIP, ASE etc would all depend on. The others are all working so this package is the last link in the chain. 

I'm in touch with the ChemFiles developer, and will check out the other two. From a quick look, Xtals.jl seems to have only "standard" XYZ without additional properties.

**Comment by cortner** [comment]
So might it make sense for them to link your code and retire theirs?

**Comment by jameskermode** [comment]
Yes, once I get BinaryBuilder.jl working to link the C code into a cross-platform JLL it should be straightforward for other packages to use this wrapper.

Do you know if a package-neutral data representation for Atoms-like data structures is emerging? I currently work with a dictionary compatible with `ACEbase.read_dict()`, which can be easily turned into JuLIP atoms.

**Comment by cortner** [comment]
There is a discussion about it at JuliaCon this Tuesday. Personally I’m not hopeful.

**Comment by jameskermode** [comment]
Anything useful come out of this? I'd be happy to move this repo to JuliaMolSim if it would fit in and increase visibility to help reduce duplication.

Meanwhile, I've got the JLL package dependencies working, so reading of extxyz files according to the new standard now works from Julia without any Python. Write support still to be finished.

**Comment by cortner** [comment]
Since last Juliacon there is starting to be more activity around JuliaMolSim. I don't think it really matters where you want to register it. But once you do I'll announce it?

**Comment by jameskermode** [comment]
`ExtXYZ.jl` is now released via JuliaRegistries/General/pull/42230.

@cortner do please go ahead and announce it. I'll be happy to add interface to other packages such as `Xtals.jl`
