### ISSUE TITLE
(Request) Support for molecular XYZs without Lattice key

### ISSUE THREAD

**Issue by joegilkes** [libAtoms/ExtXYZ.jl#16]
Hi James,

I was just wondering if there would be any interest in making this compatible with extXYZ files that don't include a Lattice key, i.e. for molecular geometries with no inherent unit cell? 

I'd really like to use this as a simple, lightweight library for doing some low-level manipulation of molecular xyz files within Julia, but unfortunately the hard requirement for a unit cell to be provided means this package won't work on those files.

Thanks!

**Comment by cortner** [comment]
Is it a problem to just provide a trivial cell, or to just ignore the cell with no PBC? Or is the issue that you want to use existing datasets that come without the cell?

**Comment by gabor1** [comment]
I would support this enhancement because it would mean that some old XYZ files could also be read (ones with empty second lines. It's not complete backwards compatibility because we still require the second line to be a sequence of <key>=<value>

**Comment by joegilkes** [comment]
That's mostly the issue yes, I'm working within a workflow that writes extXYZs from one program and I want to read/manipulate/write them within Julia. It would definitely be possible to prepend/remove the Lattice key as necessary, it would just feel a bit clunky to have to do so.

I'm up for looking into the code and seeing if I can get it working solely within the package. For the most part it appears like it would be simple, but I'm not familiar with the C backend so I can't predict how the call to `extxyz_write_ll` would be handled in the event that there wasn't a Lattice key in the info dict. I'll take a look tomorrow and report back.

**Comment by joegilkes** [comment]
Appears to be a simple fix, opened PR #17.

**Comment by jameskermode** [comment]
v0.1.5 tagged and released
