### ISSUE TITLE
interface for arbitrary properties

### ISSUE THREAD

**Issue by JanHab** [libAtoms/ExtXYZ.jl#20]
Hello. I am wondering if we should add functionalities for the  AtomsBase interface to get the arbitrary data stored in atom_data or system_data similar to AtomsBase.
In AtomsBase you cann add arbitrary information per Atom and per System. Therefore a Dict is used for each Atom and for the System.
This means all information of the System (or Atom), without the mandatory information(like bounding_box or boundary_conditions for the system) are stored in the Dict.
In ExtXYZ, if you call system_data you, get all information in system_data, included the information about bounding_box and boundary_conditions.

I think it would be great to add two functions:
- data(atom::Atoms)
- data(atom::Atoms, i)
to get information of the system or of each Atom similar to AtomsBase.

What do you think about this?

**Comment by jameskermode** [comment]
Good suggestion, I’d be happy to add these routines. PR would be welcome.

**Comment by JanHab** [comment]
Okay great, I will do this and create a PR

**Comment by JanHab** [comment]
Okay, i think a problem here is that AtomsBase does not have such a routine yet.
There you can use `getproperty` and `propertynames`.
However, `propertynames` just returns `atom_data` and `system_data` in the ExtXYZ AtomsBase interface, so by using `getproperty` one can just get `atom_data` and `system_data` but not the data itself.

Maybe one could update `propertynames(system)` to get the propertynames of the system_data and if this is used with an index to get the propertynames of atom_data?
I think using getproperty with an index is not possible in AtomsBase yet, but i am not sure about this.

This is why i think the best way to solve this would be to add new routines to get these information.
Maybe with `data(atom::Atoms)` or with another routine.
If this is changed here, this should be adapted in a way that it works the same way in AtomsBase, so i think a PR would be needed there, too.

Any ideas about this? @jameskermode @mfherbst

**Comment by mfherbst** [comment]
This has been done in #29
