### ISSUE TITLE
show_system for AtomsBase interface

### ISSUE THREAD

**Issue by JanHab** [libAtoms/ExtXYZ.jl#21]
Hello. I think it would be nice to add a Base.show function similar to the way it is done in AtomsBase.
In this routine the atomic_symbols, the box, and if all boundary_conditions are the same, the boundary_conditions are showed.
Additionally, at the beginning, there is written whether the system is a FlexibleSystem or a FastSystem.
If one just creates an atomic_system in AtomsBase, there is a FlexibleSystem created. 

I am not complete sure if ExtXYZ would create a system similar to a FlexibleSystem or a FastSystem?

I would like to add this function, any thoughts on this?

**Comment by jameskermode** [comment]
Happy to add this. The idea of the ExtXYZ.Atoms struct is that it is both flexible and fast, since the type information for all properties is included in the parametric type definition.

**Comment by JanHab** [comment]
Okay so that means we would skip the part where it is showed which kind of system it is?

**Comment by jameskermode** [comment]
Yes that sounds right - I should have a look at what the text output looks like, but if you are willing to implement this I'll try it out

**Comment by JanHab** [comment]
In AtomsBase they do this for both, FastSystem and FlexibleSystem, by using their routine show_system.
I think it is possible to do the same here.

function Base.show(io::IO, system::Atoms)
    print(io, "System")
    AtomsBase.show_system(io, system)
end

seems to work.
In AtomsBase the "System" in the print is "FastSystem" or "FlexibleSystem", I am not sure about the best name for it in this case.

In a case where I tried this the system was showed like this:
System(Mn₃Si, AtomsBase.Periodic, box=[[3.99986972, 0.0, 0.0], [1.9999348600000004, 3.463988789348149, 0.0], [1.9999348600000004, 1.1546629297827167, 3.2658799505363403]]u"Å")

If i am not forgetting anything important here I think it could work with this code example, depending on how to call the system.

**Comment by jameskermode** [comment]
Should the name not just be `Atoms()` to match the struct name?
________________________________
