### ISSUE TITLE
Rename properties in AtomsBase Interface

### ISSUE THREAD

**Issue by JanHab** [libAtoms/ExtXYZ.jl#24]
Hello, i wonder why you didn't use the AtomsBase names for the properties in atom_data and system_data.
Wouldn't it be good to rename "box" to "bounding_box", "positions" to "position", "atomic_symbols" to "atomic_symbol", and so on.
I just tried it with a few of these properties and for those i've tried it, it seems to work.

Are the names you used important for something or would it be possible to change them, and if so, would you welcome to have this names changed @jameskermode?

**Comment by mfherbst** [comment]
This has been done in #29
