### ISSUE TITLE
Segfault when reading non-existent file

### ISSUE THREAD

**Issue by mfherbst** [libAtoms/ExtXYZ.jl#27]
if `"bla.extxyz"` does not exist this
```julia
using ExtXYZ
ExtXYZ.read_frame("bla.extxyz")
```
yields a segfault. Same does `read_frames`. An empty file is fine, though.

**Comment by jameskermode** [comment]
Thanks for reporting. I’ll add a check for this.

**Comment by jameskermode** [comment]
I can't reproduce this, unfortunately. I get an exception:

```julia
julia> using ExtXYZ
julia> ExtXYZ.read_frame("bla.extxyz")
ERROR: file bla.extxyz cannot be opened for reading
Stacktrace:
  [1] error(s::String)
    @ Base ./error.jl:35
  [2] #19
    @ ~/.julia/dev/ExtXYZ/src/fileio.jl:343 [inlined]
  [3] cfopen(f::ExtXYZ.var"#19#20"{Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}}, String, Vector{Int64}}, filename::String, mode::String)
    @ ExtXYZ ~/.julia/dev/ExtXYZ/src/fileio.jl:27
  [4] cfopen
    @ ~/.julia/dev/ExtXYZ/src/fileio.jl:25 [inlined]
  [5] #read_frames#18
    @ ~/.julia/dev/ExtXYZ/src/fileio.jl:342 [inlined]
  [6] read_frames
    @ ~/.julia/dev/ExtXYZ/src/fileio.jl:341 [inlined]
  [7] #read_frames#21
    @ ~/.julia/dev/ExtXYZ/src/fileio.jl:348 [inlined]
  [8] read_frames
    @ ~/.julia/dev/ExtXYZ/src/fileio.jl:348 [inlined]
  [9] #read_frame#9
    @ ~/.julia/dev/ExtXYZ/src/fileio.jl:287 [inlined]
 [10] read_frame
    @ ~/.julia/dev/ExtXYZ/src/fileio.jl:287 [inlined]
 [11] #read_frame#10
    @ ~/.julia/dev/ExtXYZ/src/fileio.jl:288 [inlined]
 [12] read_frame(file::String)
    @ ExtXYZ ~/.julia/dev/ExtXYZ/src/fileio.jl:288
 [13] top-level scope
    @ REPL[13]:1
```

Perhaps you could check if `ExtXYZ.cfopen("missing_file.extxyz", "r")` returns `C_NULL` on your machine?

**Comment by mfherbst** [comment]
Indeed it does return `C_NULL` for me.

**Comment by jameskermode** [comment]
That’s expected and is what is checked for when raising the error I pasted above. Not sure where the segfault occurs, then. Are you able to get a stack trace?

**Comment by mfherbst** [comment]
Not it literally just segfaults.  precise output:
```
julia> using ExtXYZ

julia> ExtXYZ.read_frame("bla.extxyz")

signal (11): Speicherzugriffsfehler
in expression starting at REPL[2]:1
_IO_fclose at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
unknown function (ip: 0x7ff5e95fc06f)
Allocations: 12138007 (Pool: 12132352; Big: 5655); GC: 12
Speicherzugriffsfehler
```

**Comment by jameskermode** [comment]
OK, that's useful, thanks - the segfault occurs when trying to `fclose()` the file, which I do in a `finally` block. 

Please can you try the candidate fix in #28 and let me know if it solves the problem? Alternatively since it looks like you're on x86_64 Linux I can try and reproduce there (so far I tested only on my arm64 MacBook which did not show this issue, likely because the standard C library is different).

**Comment by mfherbst** [comment]
Looks good.

**Comment by jameskermode** [comment]
Thanks for reporting. v0.1.9 incorporates this fix and has been tagged and released to General.
