### ISSUE TITLE
JuLIP Dependency

### ISSUE THREAD

**Issue by cortner** [libAtoms/ExtXYZ.jl#3]
I think it may be worth removing the JuLIP dependency. There is some discussion about implementing a few abstract atoms and structure interfaces that will be shared, that that one could depend on, but JuLIP will not be taken up by the community. I'll most likely retire it in the near future. Instead - until then - we can import ExtXYZ.jl from JuLIP and add JuLIP-specific wrappers.

**Comment by jameskermode** [comment]
Good idea- that was roughly my plan. I’ll separate the JuLIP stuff and make a PR

**Comment by jameskermode** [comment]
In fact I see the file IO code in JuLIP is imported from `ACEbase.FIO` and then re-exported by JuLIP. Would it be better for me to make a PR against ACEbase rather than JuLIP?

**Comment by jameskermode** [comment]
Never mind, I see that nothing in `ACEbase` is specific to Atoms, so it should go somewhere near `JuLIP.FIO.read_dict()`.

**Comment by cortner** [comment]
Correct, ACEbase was just created to put some codes that I need in ACE and JuLIP since I've disentangled ACE now completely from being about Atoms. 

I also don't mind if you want to create a JuLIP.XYZ submodule. Happy either way.

**Comment by jameskermode** [comment]
Closed by JuliaMolSim/JuLIP.jl#142
