### ISSUE TITLE
Read error 

### ISSUE THREAD

**Issue by JPDarby** [libAtoms/ExtXYZ.jl#44]
I get a segfault trying to read .xyz files with ExtXYZ version 0.1.13.

I think it's caused by extxyz_jll version 0.1.3+0 because if I downgrade that to 0.1.0+0 everything works.

**Comment by jameskermode** [comment]
Oops. I know why this is and will fix ASAP. I just did the update to  ExtXYZ_jll to add support for plain XYZ format. As an interim fix I'll change Project to use old  jll version.

**Comment by jameskermode** [comment]
Should be fixed by #45. Once CI completes I'll do a new release of ExtXYZ to stop this affecting others.

**Comment by JPDarby** [comment]
thanks

**Comment by jameskermode** [comment]
Seems to work - would you be happy to use `ExtXYZ.jl` `dev`-ed for now, and I'll do a new release later once I've added the small extra bit of code needed to resolve #35?

**Comment by cortner** [comment]
dev doesn't work for me but downgrading `extxyz_jll` does.

**Comment by jameskermode** [comment]
I hadn't merged the PR. Dev really should work now. I'll do a new release within the next day or two.

**Comment by jameskermode** [comment]
New release v0.1.14 now made to General. Please re-open if issue persists.
